apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: emottak-test-client-backend
  namespace: team-emottak
  labels:
    team: team-emottak
spec:
  ingresses:
    - https://emottak-test-client-backend.dev.intern.nav.no
  image: {{image}}
  port: 13001
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: "1000m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
  accessPolicy:
    inbound:
      rules:
        - application: emottak-test-client
    outbound:
      rules:
        - application: emottak-test-client
  envFrom:
    - secret: emottak-test-client
  env:
    - name: EMOTTAK_LOGGING_LEVEL
      value: DEBUG