apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: emottak-test-client
  namespace: team-emottak
  labels:
    team: team-emottak
spec:
  ingresses:
    - https://emottak-test-client.dev.intern.nav.no
  image: {{image}}
  port: 3000
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: "1000m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
  accessPolicy:
    inbound:
      rules:
        - application: emottak-test-client-backend
    outbound:
      rules:
        - application: emottak-test-client-backend
  env:
    - name: TEST_CLIENT_BACKEND_BASE_URL
      value: "https://emottak-test-client-backend.dev.intern.nav.no"