apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: emottak-test-client
  namespace: team-emottak
  labels:
    team: team-emottak
spec:
  ingresses:
    - https://emottak-test-client.intern.dev.nav.no
#    - https://emottak-test-client.ansatt.dev.nav.no Add this if frontend is moved to GCP
  image: {{image}}
  port: 3000
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      memory: "256Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
  accessPolicy:
    inbound:
      rules:
        - application: emottak-test-client-backend
    outbound:
      rules:
        - application: emottak-test-client-backend
  env:
    - name: TEST_CLIENT_BACKEND_BASE_URL
      value: "https://emottak-test-client-backend.intern.dev.nav.no"