hostName: ${NAIS_CLUSTER_NAME:-local}
ebmsSyncRouterUrl: "https://ebms-sync-router.intern.dev.nav.no/ebxml/msh"
smtpTransportUrl: ${SMTP_TRANSPORT_URL:-http://smtp-transport}
alias: "ARBEIDS- OG VELFERDSETATEN"
signing:
  key: ${VIRKSOMHETSSERTIFIKAT_SIGNERING:-}
  password: ${KEYSTORE_PWD_2025}
  path: ${KEYSTORE_FILE_SIGN_2025_PATH}
server:
  port: 13001
  preWait: "5s"
kafka:
  bootstrapServers: ${KAFKA_BROKERS:-localhost:9092}
  topic: ${KAFKA_TOPIC:-team-emottak.smtp.in.ebxml.payload}
kafkaOut:
  bootstrapServers: ${KAFKA_BROKERS:-localhost:9092}
  topic: ${KAFKA_PAYLOAD_TOPIC:-team-emottak.smtp.out.ebxml.payload}
