name: Build and deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**/**.md'
      - '.gitignore'
      - 'LICENCE'

env:
  MODULE_NAME: "emottak-test-client"
  IMAGE_NAME: "ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}"
  NAIS_MANIFEST: "frontend.yaml"
  PRODUCTION: true # used to prevent frontend from attempting to connect backend during build

jobs:
  build-and-push:
    name: Build, push emottak-test-client image (frontend)
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Build ${{ env.MODULE_NAME }}
        run: ./gradlew buildFrontend

      - name: "Login to GitHub Packages Docker Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push ${{ env.MODULE_NAME }} docker image"
        run: |
          docker build --tag ${{ env.IMAGE_NAME }} -f frontend/Dockerfile ${{ env.MODULE_NAME }} --pull 
          docker push ${{ env.IMAGE_NAME }}

  deploy-to-dev:
    name: Deploy emottak-test-client to dev
    needs: build-and-push
    if: github.event.inputs.environment == 'dev-fss'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy frontend to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/frontend.yaml
          VAR: image=${{env.IMAGE_NAME}}