name: "Frontend: Build and deploy"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**/**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'backend/**'

env:
  PRODUCTION: true

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      repository-projects: write
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Build frontend
        run: ./gradlew buildFrontend
        env:
          PRODUCTION: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: nais/docker-build-push@v0
        id: docker-push-frontend
        with:
          team: team-emottak
          tag: ${{ github.sha }}
          dockerfile: frontend/Dockerfile
          docker_context: frontend
          image_suffix: frontend
    outputs:
      frontendimage: ${{ steps.docker-push-frontend.outputs.image }}

  deploy-frontend:
    name: Deploy emottak-test-client to dev
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Deploy frontend to DEV
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/frontend.yaml
          IMAGE: ${{ needs.build.outputs.frontendimage }}
