name: Build and deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**/**.md'
      - '.gitignore'
      - 'LICENCE'
jobs:
  build-and-push:
    name: Build, push emottak-test-client image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./gradlew buildAll
      - name: Deploy to NAIS
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: team-emottak
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          image_suffix: ${{ github.event.inputs.environment }}
      outputs:
        image: ${{ steps.docker-build-push.outputs.image }}
  deploy-to-dev:
    name: Deploy emottak-test-client to dev
    needs: build-and-push
    if: github.event.inputs.environment == 'dev-fss'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/app.yaml
          VAR: image=${{ steps.docker-build-push.outputs.image }}